name: run main.py

on:
  schedule:
    - cron: '*/30 * * * *' # Runs cron job every half an hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          openAiAPIKEY: ${{ secrets.OPENAIAPIKEY }}
          notionToken: ${{ secrets.NOTIONTOKEN }}
          jobDBdatabaseID: ${{ secrets.JOBDBDATABASEID }}
          rawDatabaseID: ${{ secrets.RAWDATABASEID }}
        run: python main.py
